version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./.postgresdata:/var/lib/postgresql/data
  redis:
    image: redis:5
    hostname: redis
    expose:
      - 6379
  web:
    restart: always
    build: .
    command: gunicorn configuration.wsgi:application --bind 0.0.0.0:8000 --workers 4 --name airtech --reload
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
      - redis
  scheduler:
    build: .
    command: python manage.py start_scheduler
    depends_on:
      - db
      - redis
    hostname: scheduler
  worker:
    build: .
    command: python manage.py rqworker default
    depends_on:
      - db
      - redis
    hostname: worker
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
