# Generated by Django 2.2.2 on 2019-06-18 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('deleted_at', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='Open', max_length=16, null=True)),
                ('origin', models.CharField(blank=True, default='Open', max_length=16, null=True)),
                ('destination', models.CharField(blank=True, default='Open', max_length=16, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('seats', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
