# Generated by Django 2.2.2 on 2019-06-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
