# Generated by Django 2.2.2 on 2019-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190618_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='abc', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(default='abc', max_length=16),
            preserve_default=False,
        ),
    ]
