# Generated by Django 2.2.2 on 2019-06-20 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0003_auto_20190618_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('deleted_at', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reservation', 'RESERVATION'), ('paid', 'PAID')], default=tickets.models.TicketStatus('RESERVATION'), max_length=16)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
