# Generated by Django 2.2.2 on 2019-06-20 09:48

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reservation', 'RESERVATION'), ('paid', 'PAID')], default=tickets.models.TicketStatus('RESERVATION'), max_length=32),
        ),
    ]
