# Generated by Django 2.2.2 on 2019-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190620_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reservation', 'RESERVATION'), ('paid', 'PAID')], default='RESERVATION', max_length=32),
        ),
    ]
