# Generated by Django 2.2.2 on 2019-06-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190620_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='flights.Flight'),
        ),
    ]
