# Generated by Django 2.2.2 on 2019-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190620_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
